Remove unwanted columns on Target object.
opentargets/platform-etl-backend pull request #214
Opened 2021-09-27 16:14 UTC by JarrodBaker

Columns `HPA_main`, `HPA_additional`, `HPA_extracellular_location` were
not being dropped. Somewhat surprising behaviour since I would have
thought that the cast to a DS removed unwanted columns.

2021-09-27 16:34 UTC, mkarmona commented
@JarrodBaker, the use of the casting to a case class does not actually execute the transformation. It is just a wrap around the full data frame to safely operate with classes and the compiler check but it keeps on the functional side.

```Scala
@ case class Gene(id: String, approvedSymbol: String) 
defined class Gene

@ val genes = targets.as[Gene] 
genes: Dataset[Gene] = [id: string, approvedSymbol: string ... 27 more fields]

@ genes.columns 
res6: Array[String] = Array(
  "id",
  "approvedSymbol",
  "biotype",
  "transcriptIds",
  "genomicLocation",
  "alternativeGenes",
  "approvedName",
  "go",
  "hallmarks",
  "synonyms",
  "symbolSynonyms",
  "nameSynonyms",
  "functionDescriptions",
  "subcellularLocations",
  "targetClass",
...

// so the meaning of using a case class is for further map because before you map the full schema is preserved
@ val mappedGenes = genes.map(identity) 
mappedGenes: Dataset[cmd1.Gene] = [id: string, approvedSymbol: string]

@ mappedGenes.columns 
res11: Array[String] = Array("id", "approvedSymbol")

@ mappedGenes.show 
+---------------+--------------+
|             id|approvedSymbol|
+---------------+--------------+
|ENSG00000002016|         RAD52|
|ENSG00000002745|         WNT16|
|ENSG00000033867|        SLC4A7|
|ENSG00000035499|       DEPDC1B|
|ENSG00000038532|       CLEC16A|
|ENSG00000051382|        PIK3CB|
|ENSG00000068137|       PLEKHH3|
|ENSG00000075826|        SEC31B|
|ENSG00000079616|         KIF22|
|ENSG00000083845|          RPS5|
|ENSG00000084628|        NKAIN1|
|ENSG00000089356|         FXYD3|
|ENSG00000099974|          DDTL|
|ENSG00000100191|        SLC5A4|
|ENSG00000101049|          SGK2|
|ENSG00000101448|         EPPIN|
|ENSG00000102409|          BEX4|
|ENSG00000102466|         FGF14|
|ENSG00000104388|         RAB2A|
|ENSG00000104419|         NDRG1|
+---------------+--------------+
only showing top 20 rows
```
I hope this resolves your doubts regarding Spark Dataset

2021-09-27 16:38 UTC, mkarmona requested changes

2021-09-27 16:38 UTC, mkarmona commented on src/main/scala/io/opentargets/etl/backend/target/GeneWithLocation.scala
> +    hpaDf.select(col("id"), col("locations")).as[GeneWithLocation]
@JarrodBaker, based on the comment I made, the correct code here could be this for the intention above

```Scala
hpaDf.as[GeneWithLocation].map(identity)
```

2021-09-28 07:22 UTC, JarrodBaker commented
> @JarrodBaker, the use of the casting to a case class does not actually execute the transformation.

Thanks for the explanation: I've amended the PR as suggested. I find that behaviour quite counter intuitive (even though it is in the scaladoc). If I see a method with the signature:

`def writeGenesAsJson(ds: Dataset[Gene]): Unit =  ???`

I would assume that what was going to be saved to disk is a `Dataset[Gene]`. Not a `Dataset[Row]` which happens to also contain the same column names/types as in `Gene`.

2021-09-28 07:24 UTC, mkarmona approved these changes

2021-09-28 07:24 UTC, merged