Change homology input path
opentargets/platform-etl-backend pull request #288
Opened 2023-03-21 09:44 UTC by ehsanb29

2023-03-29 08:38 UTC, mbdebian requested changes
Good progress @ehsanb29 !
Please, have a look at the requested changes and re-submit the PR review request when done.

2023-03-29 13:21 UTC, ehsanb29 reviewed
All the changes is done i the next commit.

2023-03-29 13:21 UTC, ehsanb29 commented on project/Dependencies.scala
Oh, I forgot to ignore it.

2023-04-20 09:41 UTC, mbdebian approved these changes
Great work!!! 🥳

2023-04-20 10:08 UTC, mbdebian commented on configuration/2023/23_04_platform.conf
Let's take this file out

2023-04-20 10:09 UTC, mbdebian commented on configuration/2023/23_04_platform_workflow.conf
Let's take this file out

2023-04-20 10:20 UTC, mbdebian approved these changes
🥳 Great work! 🥳

2023-04-20 10:21 UTC, merged