Breaking drug step outputs into 'drug', 'mechanism_of_action', and 'indications'
opentargets/platform-etl-backend pull request #73
Opened 2020-12-21 12:10 UTC by JarrodBaker

Relates to opentargets/plaform#1306. The output name of mechanism_of_action is so that it is compliant with Elasticsearch's index naming rules. 

Also in this PR:
- Fixed deprecated warning on `elasticseach_loader`

2020-12-21 17:23 UTC, mkarmona requested changes
the output of the drugs would need to be a struct with at least 3 internal outputs drugs, moas and indications. The reason for that is the case you want to use the DFs from your step. This will also cause

1. double-check any drug-dependant step what needs either indications or MOAs by ex. search 
2. fix the other steps' code

2021-01-06 13:35 UTC, cmalangone approved these changes

2021-01-06 13:38 UTC, cmalangone requested changes
Please let me know when Miguel's request is done

2021-01-11 15:57 UTC, mkarmona approved these changes

2021-01-11 15:58 UTC, merged