feat: new default datatypeId and custom per datasourceId section
opentargets/platform-etl-backend pull request #99
Opened 2021-02-23 15:15 UTC by mkarmona

- datatypeId defaults to "other"
- datasource section can optionally have a datatypeId field to configure for that specific one

Closes /opentargets/platform/issues/1410

2021-02-23 15:33 UTC, d0choa commented
Is there any reason, why you didn't configure the datasources that are not `genetic_associations`? It would help to configure all current datasources, so we can remove `datatypeId` from the evidence in an upcoming release and not having to touch the configuration.

2021-02-25 14:30 UTC, mkarmona commented
@d0choa we need it that way as currently, the problem is just with those. When we run with the new ones we include all configurations.

2021-03-10 11:37 UTC, cmalangone commented on src/main/scala/io/opentargets/etl/Main.scala
> -      case "evidenceProteinFix" =>
It might be the case to leave evidenceproteinFix

2021-03-10 11:38 UTC, cmalangone commented on src/main/scala/io/opentargets/etl/backend/EvidenceProteinFix.scala
> -package io.opentargets.etl.backend
@mkarmona This file might be useful

2021-03-10 11:40 UTC, cmalangone commented on src/main/resources/reference.conf
> -// DEPRECATED this is a temporal fix that have to be removed eventually
@mkarmona This should stay too,

2021-03-10 11:46 UTC, cmalangone approved these changes

2021-03-10 12:17 UTC, JarrodBaker requested changes

2021-03-10 12:17 UTC, JarrodBaker commented on src/main/resources/reference.conf
> +      {k: "header", v: "true"}
We should add another k,v here: `{k: "comment", v: "#"}` to have Spark remove the comment lines at the top of the file automatically. 

From the docs
```
   * <li>`comment` (default empty string): sets a single character used for skipping lines
   * beginning with this character. By default, it is disabled.</li>
   * ```
We can then remove the manual filtering in Interactions

2021-03-10 12:17 UTC, JarrodBaker commented on src/main/scala/io/opentargets/etl/backend/Interactions.scala
> +    val ensProtein = ensProteinFile.zipWithIndex().filter(x => x._2 > 4).map(x => x._1).toDF
We can update `reference.conf` and we don't need line 359.

2021-03-10 12:51 UTC, merged